name: "ğŸ‘™ Feature"
description: "ì–´ë–¤ ê¸°ëŠ¥ì„ ë§Œë“œì…¨ëŠ”ì§€ ì•Œë ¤ì£¼ì„¸ìš” !"
labels: "ğŸ‘™ Feature"
body:
  - type: textarea
    attributes:
      label: ğŸ“ Desc
      description: ì–´ë–¤ ê¸°ëŠ¥ì„ í•˜ëŠ”ì§€ ì•Œë ¤ì£¼ì„¸ìš” !
      placeholder: ì‹¤ì œ ì˜ˆì‹œë¥¼ ë“¤ì–´ì£¼ë©´ ì¢‹ì•„ìš”.
    validations:
      required: true
  - type: textarea
    attributes:
      label: âœ… Todos
      description: ê¸°ëŠ¥ êµ¬í˜„ì„ ìœ„í•´ í•´ì•¼í•  ì¼ì„ ì‘ì„±í•´ì£¼ì„¸ìš”.
      placeholder: í•¨ìˆ˜, ì»´í¬ë„ŒíŠ¸, í˜ì´ì§€ ë“±ë“±.. ì ì–´ì¤˜ë„ ì¢‹ì•„ìš”.
    validations:
      required: true
  - type: textarea
    attributes:
      label: ğŸ§â€â™‚ï¸ Etc...
      description: í•˜ê³ ì‹¶ì€ ì–˜ê¸°ê°€ ìˆë‚˜ìš” ?
